### ISSUE TITLE
Error code 400

### ISSUE THREAD

**Issue by jmigdelacruz** [anthony19114/mybitcoinzwallet#1]
Trying to send from web wallet all fields correctly have input and "send btcz" checkbox is ticked but i get a status error code 400 everytime i try to send.

**Comment by anthony19114** [comment]
Make sure you only put fee 0.0001

Error code means rejected by blockchain. Either was a bad address or too high of a fee.

For example:
2017-10-12 00:05:23 ERROR: AcceptToMemoryPool: absurdly high fees

**Comment by jmigdelacruz** [comment]
Awesome. Put in 0.0001 and it worked perfectly.

Thanks anthony.
