### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by brokerexio** [anthony19114/mybitcoinzwallet#2]
I’ve clicked on index.html on dist folder.
It appears zencash wallet generator.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anthony19114** [comment]
Perhaps someone has interest in making it work locally, the files to run local are in the dist/ folder.
Then submit a pull request.

**Comment by anthony19114** [comment]
Updated
